id: P006830
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG26110
  title: རྟོག་འགྱུ།
  author: ''
  volumes:
    b8aea410b02f420b81c6460d4cd1360a:
      image_group_id: I1KG26340
      title: ''
      volume_number: 1
      total_pages: 210
