id: P006830
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-17 12:25:24.573121
source_metadata:
  id: bdr:W1KG26110
  title: རྟོག་འགྱུ།
  author: ''
  volumes:
    b8aea410b02f420b81c6460d4cd1360a:
      image_group_id: I1KG26340
      title: ''
      volume_number: 1
      total_pages: 210
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
